# Packages that will be needed for workshop students
## CRAN packages
library(RPostgres)
library(readr)
library(dplyr)
library(dbplyr)
library(janitor)
library(shiny)
library(ggplot2)
library(tidyr)
library(purrr)
library(lubridate)
library(forcats)
library(bslib)
library(shinyvalidate)
library(rsconnect)
library(cicerone)
library(conductor)
library(waiter)
library(progressr)
library(plumber)
library(dbplyr)
library(DBI)
library(glue)
library(config)
library(dm)
library(whereami)
library(logger)
library(plotly)
library(crosstalk)
library(fontawesome)
library(here)
library(shinylogs)
library(shinyloadtest)
library(withr)
library(fs)
library(reactlog)
library(dbplot)
library(pins)
library(paws.storage)
library(reactable)
library(RSQLite)
library(pool)
library(golem)
library(rhino)
library(DT)
library(thematic)
library(shinyjs)
library(httr2)
library(shinipsum)
library(dockerfiler)

## GitHub (dev) packages
# renv::install("rstudio/connectapi")
library(connectapi)

# renv::install("rpodcast/shinyprod")
library(shinyprod)

# renv::install("ewenme/shinya11y")
library(shinya11y)

# Packages needed for my dev of the course (all of the above plus these extra)
## CRAN packages
library(languageserver)
library(httpgd)
library(rstudioapi)
library(quarto)
library(grDevices)
library(furrr)
library(progressr)

## GitHub (dev) packages
# renv::install("gadenbuie/countdown")
library(countdown)

# renv::install("cloudyr/googleCloudVisionR")
library(googleCloudVisionR)